name: property-group-4-ai-policy
version: 1
description: >-
  Machine-readable policy for AI agents operating on this repository. The
  entries below are actionable steps that an AI must perform when modifying the
  codebase. Placeholders such as `${modified_file}` will be populated by the
  orchestrator.

rules:
  - id: codacy_post_edit_analysis
    description: "After any file edit (create/update/delete), run Codacy analysis for each modified file and fix reported issues before proceeding."
    required: true
    steps:
      - run: codacy_cli_analyze
        args:
          rootPath: "."
          file: "${modified_file}"
        on_failure: propose_and_apply_fixes

  - id: trivy_after_package_change
    description: "When `package.json` or lockfiles change, run Trivy (via Codacy CLI) and block further edits if high/critical vulnerabilities are found."
    required: true
    triggers:
      - file_patterns:
          - backend/package.json
          - frontend/package.json
          - "**/pnpm-lock.yaml"
    steps:
      - run: pnpm --filter backend exec -- codacy_cli_analyze
        args:
          rootPath: "."
          tool: trivy
        on_failure: stop_and_propose_fixes

  - id: run_typescript_checks
    description: "Run TypeScript checks for packages that changed."
    required: true
    triggers:
      - file_patterns:
          - "backend/**/*.ts"
          - "frontend/**/*.ts"
          - "frontend/**/*.tsx"
    steps:
      - run: pnpm --filter backend exec tsc -p backend || true
      - run: pnpm --filter frontend exec tsc -p frontend || true

  - id: secrets_handling
    description: "If secrets are present, remove them from the index and escalate to maintainers. Do not push secrets to remote."
    required: true
    steps:
      - action: detect_secrets
      - run: |
          git rm -r --cached backend/.env || true
          git commit -m "chore: remove secrets from index (automated)" || true
        on_failure: notify_maintainers

  - id: minimal_diffs
    description: "Avoid unrelated or large reformatting changes. Keep changes focused on required files."
    required: true

  - id: todo_workflow
    description: "Use the repository TODO workflow: create tasks with `manage_todo_list`, set exactly one todo to `in-progress`, complete it before starting the next."
    required: true

metadata:
  maintainers:
    - name: Angel
      contact: TODO:replace-with-maintainer-email-or-username
  recommendations:
    - "When editing backend code, prefer running: `pnpm --filter backend exec tsc -p backend`"
    - "When adding dependencies for backend: `pnpm --filter backend add <pkg>` then run Trivy via Codacy CLI"
  examples:
    generate_types: "supabase gen types typescript --project-id <PROJECT_ID> --schema public > backend/src/types/database.ts"
    codacy_run: "codacy_cli_analyze --rootPath . --file backend/src/models/property.ts"
    trivy_run: "pnpm --filter backend exec -- codacy_cli_analyze --rootPath . --tool trivy"
