version: "3.8"

services:
  backend:
    build:
      context: .
      target: production
    container_name: property_group_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
